include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: error
    prefer_const_declarations: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
