name: my_muuri
description: "Thanks for visiting my portfolio project!💬 Feel free to explore, give feedback, or connect with me through the provided links! 🚀"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

#------------ PACKAGE ------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packges
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  loading_animation_widget: ^1.3.0

  # Fonts
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  lottie: ^3.3.1

  # State Management
  provider: ^6.1.2

  # Mailto
  mailto: ^2.0.0

  # Json
  json_annotation: ^4.9.0

  # Connectivity Checker
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

#------------ ./ PACKAGE END ------------#

#------------ FLUTTER ICONS LAUNCHER ------------#
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logos/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logos/logo.png"
#------------ ./ FLUTTER ICONS LAUNCHER END------------#

flutter:
  uses-material-design: true

  #------------ LOCAL ASSETS ------------#
  assets:
    # env
    - .env

    # Images
    - assets/images/
    - assets/images/profile.jpg
    - assets/images/banner.png

    # Images Certificate
    - assets/images/certificate/BELAJAR-BACKEND-PEMULA-UNTUK-JAVASCRIPT.webp
    - assets/images/certificate/BELAJAR-DASAR-DASAR-DEVOPS.webp
    - assets/images/certificate/BELAJAR-DASAR-MANAJEMEN-PROYEK.webp
    - assets/images/certificate/BELAJAR-DASAR-PEMOGRAMAN-WEB.webp
    - assets/images/certificate/BELAJAR-DASAR-STRUCTURED-QUERY-LANGUAGE-(SQL).webp
    - assets/images/certificate/BELAJAR-FUNDAMENTAL-APLIKASI-FLUTTER.webp
    - assets/images/certificate/BELAJAR-MEMBUAT-APLIKASI-FLUTTER-UNTUK-PEMULA.webp
    - assets/images/certificate/CERTIFICATE-BTI-ENERGY.png
    - assets/images/certificate/CLOUD-PRACTITIONER-ESSENTIALS.webp
    - assets/images/certificate/DART-FLUTTER-DEVELOPMENT-BOOTCAMP-FIND-HOUSE-APP.webp
    - assets/images/certificate/MEMULAI-PEMOGRAMAN-DENGAN-PYTHON.webp
    - assets/images/certificate/MEMULAI-DASAR-PEMOGRAMAN-UNTUK-MENJADI-PENGEMBANGSOFTWARE.webp
    - assets/images/certificate/MEMULAI-PEMOGRAMAN-DENGAN-DART.webp
    - assets/images/certificate/MSIB-PROJECT-MANAGEMENT.webp
    - assets/images/certificate/CHEVALIER-LAB.webp
    - assets/images/certificate/PANITIA-TELKOM.webp
    - assets/images/certificate/PT-SINTECH-FLUTTER.webp
    - assets/images/certificate/SCHOLARSHIP4US.webp

    # Json
    - assets/json/certificate.json
    - assets/json/android.json
    - assets/json/coming_soon.json

    # Icons

    # Logos
    - assets/logos/logo.png
